# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_run:
    workflows: [CodeQL]
    types: [completed]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle build
      uses: gradle/gradle-build-action@v2.2.1
      with:
        gradle-version: current
    - run: gradle build    

    - name: Publish Test Report - JUnit table
      uses: dorny/test-reporter@v1.5.0
      if: always()    # run this step even if previous step failed
      with:
        name: JUnit Test results            # Name of the check run which will be created
        path: build/test-results/test/TEST-*.xml    # Path to test results
        reporter: java-junit        # Format of test results
