# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle build
      uses: gradle/gradle-build-action@v2.2.1
      with:
        gradle-version: current
    - run: gradle build    
    
    - name: Get Test Results history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        persist-credentials: false
        fetch-depth: 0

    - name: Create Test Results History
      uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
      if: always()
      id: allure-report
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        WORKFLOW_ID: main.yml
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        
    - name: Enforce permission requirement
      uses: prince-chrismc/check-actor-permissions-action@v2
      with:
        permission: write

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test Results Link'
          state: 'success'
          sha: ${{ github.sha }}
          target_url: https://safinalu.github.io/testcontainers-test-gradle/${{ github.run_number }}
          
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.2.0
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

    - name: Test Report - JUnit table
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JUnit Test results            # Name of the check run which will be created
        path: build/test-results/test/TEST-*.xml    # Path to test results
        reporter: java-junit        # Format of test results
        
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: allure-report/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.GH_MAIL }}
        GH_NAME: ${{ github.repository_owner }}

